server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: YMXymx.945
  servlet:
    multipart:
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 100MB #设置单个文件大小

#配置邮箱发送验证码
  mail:
    host: smtp.163.com
    default-encoding: UTF-8
    username: YMX9451@163.com
    password: OINIQSYFMSYIFJYE
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            class: java.net.ssl.SSLSocketFactory

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

#定义文件上传保存的路径,reggie名字可以自己定义
reggie:
  path: /usr/local/resources/reggie_take_out/